//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringerExpress.Forms {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpData() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringerExpress.Forms.HelpData", typeof(HelpData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Switch$Yeni_Kayıt_Oluşturmak$Kayıt_Çalıştırmak benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FileNames {
            get {
                return ResourceManager.GetString("FileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;h1&gt;Kayıt Çalıştırmak&lt;/h1&gt;
        ///&lt;p&gt;
        ///    Yeni bir kayıt çalıştırmak için switch menüsünden favori bir kayda tıklayarak çalıştırabilirsiniz.
        ///    Yada Windows bildirim çubuğundan &quot;Stringer Express&quot; ikonuna sağ tıklayarak &quot;Listele&quot; seçeneğini seçip,
        ///    ilgili kayda sağ tıklayıp &quot;Çalıştır&quot; seçeneği ile çalıştırabilirsiniz.
        ///&lt;/p&gt;
        ///&lt;h1&gt;Kayıt çalıştığında&lt;/h1&gt;
        ///&lt;p&gt;
        ///    Sol altta kırmızı renkli bir gösterge açılacaktır.
        ///    Göstergede örnek olarak &quot;0/3&quot; gibi bir yazı yazar. Bunun anlamı 3 kez kopyalama yapmanız ge [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Kayıt_Çalıştırmak {
            get {
                return ResourceManager.GetString("Kayıt_Çalıştırmak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;link href=&quot;{0}&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;h1&gt;Switch Menüsü&lt;/h1&gt;
        ///&lt;p class=&quot;text-danger&quot;&gt;
        ///    Favori kayıtların bulunduğu menüdür.
        ///    Hızlıca bu menüye ulaşarak favori kayıtlarınızı çalıştırabilirsiniz.
        ///    Menüdeki + butonu ile yeni kayıt oluşturabilirsiniz.
        ///    Menüyü açmak için &lt;kbd&gt;CTRL+SHIFT+C&lt;/kbd&gt; kısayolunu kullanabilirsiniz.
        ///&lt;/p&gt; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;h1&gt;Yeni Kayıt Oluşturmak&lt;/h1&gt;
        ///&lt;b&gt;Kayıt Penceresi Açmak için&lt;/b&gt;
        ///&lt;p&gt;Switch menüsünden + işaretli butona tıklayabilirsiniz.&lt;/p&gt;
        ///&lt;p&gt;Yada Windows bildirim çubuğunda &quot;Stringer Express&quot; ikonuna sağ tıklayarak &quot;Yeni Kayıt&quot; seçeneği üzerinden yeni kayıt oluşturabilirsiniz.&lt;/p&gt;
        ///&lt;b&gt;Kayıt Oluşturmak&lt;/b&gt;
        ///&lt;p&gt;
        ///    İsim kısmı üzerinden kayda bir isim veriniz.
        ///    Metin kısmına metninizi yapıştırdığınızda ne görmek istiyorsanız yazınız.
        ///    Kopyalayacağınız metinlerin olması gerektiği yerlere &quot;{0}&quot; şeklinde numara [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Yeni_Kayıt_Oluşturmak {
            get {
                return ResourceManager.GetString("Yeni_Kayıt_Oluşturmak", resourceCulture);
            }
        }
    }
}
