//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringerExpress.Forms {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpData() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringerExpress.Forms.HelpData", typeof(HelpData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Switch$Yeni_Kayıt_Oluşturmak benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FileNames {
            get {
                return ResourceManager.GetString("FileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch Menüsü
        ///	Favori kayıtların bulunduğu menüdür. 
        ///	Hızlıca bu menüye ulaşarak favori kayıtlarınızı çalıştırabilirsiniz.
        ///	Menüdeki + butonu ile yeni kayıt oluşturabilirsiniz.
        ///	Menüyü açmak için CTRL+SHIFT+C kısayolunu kullanabilirsiniz.
        ///	 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Kayıt Oluşturmak
        ///	Kayıt Penceresi Açmak için
        ///		Switch menüsünden + işaretli butona tıklayabilirsiniz.
        ///		Yada Windows bildirim çubuğunda &quot;Stringer Express&quot; ikonuna sağ tıklayarak &quot;Yeni Kayıt&quot; seçeneği üzerinden yeni kayıt oluşturabilirsiniz.
        ///	Kayıt Oluşturmak
        ///		 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Yeni_Kayıt_Oluşturmak {
            get {
                return ResourceManager.GetString("Yeni_Kayıt_Oluşturmak", resourceCulture);
            }
        }
    }
}
